version: '3'

services:
  api:
    container_name: brainny_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/
    ports:
      - "5050:5050"
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    container_name: brainny_db
    image: postgres:11.5
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data: